apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoicnlhbi5rZm9yZEBpY2xvdWQuY29tIiwicGFzc3dvcmQiOiJnaHBfODY3akFPNjFWN1E2YWZ5RWVNRW0zTmxaZTh3QlJrMURKQk5PIiwiZW1haWwiOiJyeWFuLmtmb3JkQGljbG91ZC5jb20ifX19
type: kubernetes.io/dockerconfigjson
